DATASET:
  root_dataset: "./data/cityscapes/"
  list_train: "./data/cityscapes/train.odgt"
  list_val: "./data/cityscapes/val.odgt"
  num_class: 19
  imgSizes: (256, )
  imgMaxSize: 2048
  padding_constant: 1
  segm_downsampling_rate: 1
  random_flip: True
  square_crop: False

MODEL:
  arch_encoder: "espnetv2"
  arch_decoder_ss: "espnetv2"
  arch_decoder_sr: "espnetv2"
  fc_dim: 768

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  beta1: 0.9
  lr_encoder: 1e-2
  lr_decoder: 1e-2
  lr_pow: 0.9
  weight_decay: 5e-4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/city-espnetv2-dual-20epoch"
