DATASET:
  root_dataset: "./data/cityscapes/"
  list_train: "./data/cityscapes/train.odgt"
  list_val: "./data/cityscapes/val.odgt"
  num_class: 19
  imgSizes: (256, )
  imgMaxSize: 2048
  padding_constant: 1
  segm_downsampling_rate: 1
  random_flip: True
  square_crop: False

MODEL:
  arch_encoder: "swin_t"
  arch_decoder: "upernet"
  fc_dim: 768

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 32
  start_epoch: 0
  epoch_iters: 5000
  optim: "AdamW"
  lr_encoder: 6e-5
  lr_decoder: 6e-5
  lr_pow: 0.9
  weight_decay: 1e-2
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_32.pth"

TEST:
  checkpoint: "epoch_32.pth"
  result: "./"

DIR: "ckpt/city-swin_t-upernet-32epoch"
